bname = "mplaylist"
ecs_access_key_id = "xxxxxxxxxxxxxxxxxx@ecstestdrive.emc.com"
ecs_secret_key = "pppppaaaaasssssswwwwwwooooorrrrrrddddddd"
ecs_host = "object.ecstestdrive.com"
access_url = "xxxxxxxxxxxxxxxxxx.public.ecstestdrive.com"
